[package]
name = "boxes"
version = "0.1.0"
authors = ["Christopher Biscardi <chris@christopherbiscardi.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "c4d1ae0a4744ebed8366ff6d4ea5bd77af878744" }
# bevy_easings = { git = "https://github.com/vleue/bevy_easings", branch = "main" }
itertools = "0.10.1"
rand = "0.8.4"
